### ISSUE TITLE
feature lost tracking

### ISSUE THREAD

**Issue by arenas7307979** [kmyid/benchmark-orientation#1]
hi,
Sometimes, when large view-point changes , the feature will lost tracking
(cannot find matching pairs)

I thinking main reason is that the dominant orientation not robust, causing cannot find the correct feature description.( excuse me, could you tell me the opinion correct or not?)

if i change methods (ex: sGLOH, MROGH, LIFT.. ) to estimate the dominant orientation, will be improved?

**Comment by kmyi** [comment]
I am not sure what you mean by "the feature". Can you be more specific?

**Comment by arenas7307979** [comment]
Sorry, 
The feature mean  _ORB,
I suggest that orientation by Intensity centroid not suitable as a dominant orientation,
or what else improvement can i solve lost tracking from view-point changes?

I appreciate your reply.

**Comment by kmyi** [comment]
@boy7307979 Can you send me an email to kwang.yi@epfl.ch? I think your question is not really related to this repo. Perhaps we can move the discussion to email.

Cheers,
Kwang

**Comment by YuYuYan** [comment]
hi
I run run_evaluate.m ,but there was an error----- from parse import parse . ImportError: No module named parse.  I use the breakpoint and saw the error display  "If we have an error from python execution, retry five times and spit error as the error might just be from theano compile issues... " 
my python 2.7.13 and I try to import parse in python,it worked. but the error still
and I have runing the LIFT, it succeed.

looking forward to your reply.thank you very much!

**Comment by kmyi** [comment]
Please do not post on a closed & unrelated issue. Open a new one.
