### ISSUE TITLE
ImportError: No module named parse

### ISSUE THREAD

**Issue by YuYuYan** [kmyid/benchmark-orientation#2]
hello  
I'm so sorry to bother again.

I run the benchmark-orientation and There was still an error: (the environment may be ok)

 from parse import parse
ImportError: No module named parse

Error using getOrientations_GHHPoolingEF (line 110)
error in python execution!

Error in evaluateDescriptors (line 330)
                        f = functionHandle1(list_img_info{i_img}, ...

Error in computeDescriptors (line 81)
        res = evaluateDescriptors(combinations{idxComb,1}, ...

Error in run_evaluate (line 129)
    computeDescriptors(parameters);
 ________________________________________________________________
**But when I run learn-orientation and  like this**

python runSingleTestWithFiles.py /home/yanyuyu/Downloads/benchmark-orientation-master/matlab/../data/Webcam/Chamonix/test/image_color/20130802_144500.png /home/yanyuyu/Downloads/benchmark-orientation-master/matlab/../data/Webcam/Chamonix/test/features/20130802_144500_EdgeFociD_keypoints-none-txt /home/yanyuyu/Downloads/benchmark-orientation-master/matlab/src/KeypointOrientations/GHHPoolingEF/prelearned/efsift-360.config  /home/yanyuyu/Downloads/benchmark-orientation-master/matlab/../data/Webcam/Chamonix/test/features/20130802_144500_EdgeFociD_keypoints_GHHPoolingEF_oriented-none-efsift-360-txt

# **And no error The result is**

Time taken to load image is 0.050669 seconds
Time taken to load kp is 1888 kps is 0.025257 seconds
Time taken to load patches for 1888 kps is 0.293315 seconds
Time taken to normalize patches for 1888 kps is 0.001916 seconds
/home/yanyuyu/Downloads/learn-orientation-release/python-code/Utils/models.py:123: UserWarning: DEPRECATION: the 'ds' parameter is not going to exist anymore as it is going to be replaced by the parameter 'ws'.
  ds=poolsize, ignore_border=True)
compiling get_output() ... done.
compiling get_raw_output() ... done.
testing... done!
Time taken to compute 1888 kps with pre-loaded patch is 0.170404 seconds
Time taken to compute for image /home/yanyuyu/Downloads/benchmark-orientation-master/matlab/../data/Webcam/Chamonix/test/image_color/20130802_144500.png (including compile time) is 1.660146 seconds

 So I think my environment is ok,right?

**Comment by YuYuYan** [comment]
And now the question has changed. I think  When I  run buildAll.sh ,and some error was happend. so I want to you give me all binaries  in matlab/external/methods . Please send this files to my mailbox, and my mailbox is yuyuyan@stumail.nwu.edu.cn, thanks.

**Comment by kmyi** [comment]
Again, please open a new issue for different problems. We tested the building process on both OSX and Linux, and as long as you have the requirements properly setup, you should be fine. Also, I think giving you binaries won't help, since the errors usually mean that you don't have the dependencies resolved, i.e. the binaries won't run anyways.

**Comment by kmyi** [comment]
For the first question, it's quite weird as what matlab does is simply doing what you did manually. Can you maybe try to print out the exact command line that causes error in the benchmark? You can probably do something like display(com) on the commandline that is executed with the system function.

**Comment by YuYuYan** [comment]
hello,I'm again. my python version 2.7.12. so I try to changed the '**from parse import parse**' to '**from urlparse import urlparse**'   in custom_types.py.  and the Error  **No module named parse** is disappear but another error appear:

### result =

WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 0: TITAN X (Pascal) (CNMeM is enabled with initial size: 70.0% of memory, cuDNN 5110)
Parameters
#--------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "runSingleTestWithFiles.py", line 66, in <module>
    param.loadParam(config_file)
  File "/home/yanyuyu/Downloads/learn-orientation-release/python-code/Utils/custom_types.py", line 123, in loadParam
#     if parse_res['parse_type'] == 'ss':
TypeError: tuple indices must be integers, not str

Thanks

**Comment by YuYuYan** [comment]
when I input !python in matlab  ,the version is python2.7.12 
but  I used python version 2.7.13. so how to set the python version is 2.7.13 in matlab?
I have try pyversion executable and it tell me isload =1,
but the error still !

**Comment by kmyi** [comment]
urlparse is not the same library. you should use parse. Also, if matlab is loading a different python, one thing you can do is to make the system call ignore matlab's paths. It depends on your operating system how you do this, but if you are on Linux, you can try echoing LD_LIBRARY_PATH, PATH, CPATH, INCLUDE_PATH, LIBRARY_PATH and such and appending then in front of the system call in the libraries.

Normally, this should not happen, as I have not experienced such issue. Any change you have PYTHON_PATH in your matlab configuration file or your bashrc? Also, one trick could also be to install parse on the matlab's python environment. you can try doing `!pip install parse` inside matlab

**Comment by YuYuYan** [comment]
my god!!! I have solve this problem.  Now I think just because my computer has four users, and the python in matlab only know the 2.7.12 by default, so i copy the parse.py file to the py2.7/ ...   

Thank you ,thank you for your reply everytime

**Comment by YuYuYan** [comment]
oh my god  you are in .
I'm sorry i should say correct and complete.
just copy the  parse.py file to the /usr/lib/python2.7/dist-packages
