### ISSUE TITLE
How can i get the matching 

### ISSUE THREAD

**Issue by YuYuYan** [kmyid/benchmark-orientation#3]
when I run the code and get the Average AUC: 0.3634 and the plot.but I want to know how can i get the matching like this:
![90d1050c-0bc0-11e7-8411-faf0f7bc8d72](https://cloud.githubusercontent.com/assets/18329773/25535763/d1eb2e26-2c6a-11e7-8c38-34c96a7580ce.png)

Thanks

**Comment by kmyi** [comment]
For that, what we did was to get nearest neighbor matches and display only the ones that are valid according to the GT. There's no code for doing that. We plan to release some example code that can do that, but we don't have much free time as of now. 

Also, the image in question is for LIFT, so it's not really relevant to this repo

**Comment by YuYuYan** [comment]
Thanks again
