### ISSUE TITLE
GHHPooling and GHHPoolingEF weights are identical

### ISSUE THREAD

**Issue by ducha-aiki** [kmyid/benchmark-orientation#4]
Chechsum

    old-ufo@oldufo-UX303UB:~/dev/benchmark-orientation/matlab/src/KeypointOrientations$ md5sum 
    GHHPooling/prelearned/efsift/layer4_W.npy GHHPooling/prelearned/efsift-360/layer4_W.npy 
    GHHPoolingEF/prelearned/efsift/layer4_W.npy GHHPoolingEF/prelearned/efsift-360/layer4_W.npy

Gives:

    fddffc7636e0aa2c7e35aa63d2310bf1  GHHPooling/prelearned/efsift/layer4_W.npy
    113c4a493176493867acefa60770856c  GHHPooling/prelearned/efsift-360/layer4_W.npy
    fddffc7636e0aa2c7e35aa63d2310bf1  GHHPoolingEF/prelearned/efsift/layer4_W.npy
    113c4a493176493867acefa60770856c  GHHPoolingEF/prelearned/efsift-360/layer4_W.np

Is this intentional? Could you also please provide weights for other models (or just the best performing) ?

**Comment by kmyi** [comment]
Nope, thank you for pointing that out. I'll add the proper sift models soon.

Cheers,
Kwang
