### ISSUE TITLE
Add SIFT models

### ISSUE THREAD

**Issue by kmyi** [kmyid/benchmark-orientation#5]

**Comment by ducha-aiki** [comment]
hi, @kmyid 
I would really appreciate, if you could upload models (at least the best performing) before CVPR deadline :)

**Comment by kmyi** [comment]
Hi,

The one with the Edge Foci keypoints is actually the best performing one. i.e. EF-SIFT-plus, EF-Daisy-star and EF-VGG-star are with this one.

I'll check tomorrow if SIFT-plus is still there and upload it. I think that pretty much is all the models that are relevant. Quite busy with CVPR at the moment here as well :-)

**Comment by ducha-aiki** [comment]
Hi,
Thanks for fast reply! The only remaining question of what is descriptor used? Edge Foci is detector. Do you mean BiCE descriptor, which also computed by Edge Foci binary?

May the CVPR Force be with you :)

**Comment by kmyi** [comment]
See the paper for details :-) We try quite a lot of combinations!

Message written with iPhone. 
Please excuse any brievity and typos.
_________  

Kwang Moo Yi, Ph.D., 
PostDoc @EPFL CVLab
Tell: +41 21 693 67 16


2017. 11. 7. 21:42, Dmytro Mishkin <notifications@github.com> 작성:

**Comment by ducha-aiki** [comment]
So it should be EF-VGG or EF-Daisy.

**Comment by kmyi** [comment]
Yes, so the model (the non deleted ones) at this repo is the one for EF-SIFT+, EF-Daisy(star), EF-VGG(star). Which is in fact the top performing combination in the paper.

Also, since the dataset we trained has limited orientations, we also further tried with random rotations augmented, which is the one with 360 suffix. However, I have the 360 model only for EF-SIFT trained model. 

The one I (hopefully) will upload tomorrow would be SIFT+ in the paper. let's hope the model did not evaporate... 

Kwang

**Comment by ducha-aiki** [comment]
Great, thanks again!

**Comment by kmyi** [comment]
Done as of v1.0.5

**Comment by ducha-aiki** [comment]
Thanks!
