### ISSUE TITLE
Is there any reason to reject the most of detectors?

### ISSUE THREAD

**Issue by ducha-aiki** [kmyid/benchmark-orientation#6]
https://github.com/kmyid/benchmark-orientation/blob/f4959ef20c9f5ce8178a77eac459b302747fa553/matlab/src/KeypointDescriptors/_VGG/getDescriptors_VGG.m#L4

**Comment by kmyi** [comment]
It's just to speed up testing. We can't test all combinations ;-)

**Comment by ducha-aiki** [comment]
OK, thanks. It just took me two hours to find why it doesn`t want to compute results for Hessian...

**Comment by kmyi** [comment]
Sad that you had to go through that :-(
